name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Branch name
        run: echo ${GITHUB_REF##*/}
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to GAE
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
            version: '290.0.1'
            project_id: "vape-survey"
            service_account_key: ${{ secrets.SERVICE_ACCT_KEY }}
            export_default_credentials: true
        run: |
            gcloud info
            gcloud app deploy --project vape-survey
        
